### PR TITLE
feat(*): step 3

### PR DESCRIPTION
**Pull request by aoudiamoncef**

### CODE REVIEW

**Comment by loicmathieu** [comment]
@aoudiamoncef can you rebase it on `step-3` please ?

**Comment by aoudiamoncef** [comment]
@loicmathieu done

**Comment by loicmathieu** [comment]
@aoudiamoncef wrong changes have slipped into this PR.
Can you rework it so only config related changes are shipped ?

**Comment by aoudiamoncef** [comment]
sorry, it's a rebase hell 😂. seems to be ok

**Comment by loicmathieu** [comment]
Yeah I knwo ;)

There is still changes on `createBookmark`, `updateBookmark` and `deleteBookmark` methods, can you undo them ?

**Comment by aoudiamoncef** [comment]
Please tell me that's ok

**Comment by loicmathieu** [comment]
OK now, thanks, merged.

**Comment by aoudiamoncef** [comment]
@loicmathieu there is a small error in this PR, we doesn't used Jboss logger

**Comment by loicmathieu** [comment]
@aoudiamoncef open another PR for this step I'll merge it before the one for step-5

**Comment by aoudiamoncef** [comment]
@loicmathieu what a hell 😂🙀, but we'll do it

**Pull request merged**
