### PR TITLE
feat(*): step 1

### PR DESCRIPTION
**Pull request by aoudiamoncef**

### CODE REVIEW

**Comment by loicmathieu** [comment]
As all PR are build one on top of the other, I will review them and merged them one by one ....
This will be a long process, but it's needed as I will also need to rebase my branches to have them all on top of the other as today ...

**Comment by aoudiamoncef** [comment]
I checked the content of the PR about 30 times. If you validate the PR step
6, all will be fine for the rest. Good luck for the merging stuff 😭

**Comment by loicmathieu** [comment]
Shouldn't this one be tergeted master ?

**Comment by loicmathieu** [comment]
Can you rebase on the latest `step-1` branche ?

**Comment by aoudiamoncef** [comment]
@loicmathieu , done

**Comment by loicmathieu** [comment]
Thanks merged.

**Pull request merged**
